apiVersion: v1
kind: Namespace
metadata:
   name: poc
   labels: 
     name: poc

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: poc
type: Opaque
stringData:
  username: "admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: poc
data:
  message: managed by k8s configMap

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: poc
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
#        command: [ "/bin/sh","-c","cat /etc/test_conf.txt" ]
        volumeMounts:
          - mountPath: /etc/test_conf.txt
            name: config-volume
          - mountPath: /etc/test_secret.txt
            name: secret-volume
      volumes:
        - name: config-volume
          configMap:
            name: special-config
            items:
              - key: message
                path: test_conf.txt
        - name: secret-volume
          secret:
            secretName: mysecret
            items:
              - key: username
                path: test_secret.txt

